# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitProxGradCpp <- function(theta, intStepSize, lambda1, dat, basisMat0, nk, Hp, maxInt, epsilon, shrinkScale, accelrt, numCovs, designMat1, truncation) {
    .Call(`_sparseSOMNiBUS_fitProxGradCpp`, theta, intStepSize, lambda1, dat, basisMat0, nk, Hp, maxInt, epsilon, shrinkScale, accelrt, numCovs, designMat1, truncation)
}

fitProxGradCppold <- function(theta, intStepSize, lambda1, dat, basisMat0, nk, sparOmega, lambda2, smoOmega1, maxInt, epsilon, shrinkScale, accelrt, numCovs, designMat1, basisMat1, truncation) {
    .Call(`_sparseSOMNiBUS_fitProxGradCppold`, theta, intStepSize, lambda1, dat, basisMat0, nk, sparOmega, lambda2, smoOmega1, maxInt, epsilon, shrinkScale, accelrt, numCovs, designMat1, basisMat1, truncation)
}

sparseOmegaCr <- function(myh, K, matF) {
    .Call(`_sparseSOMNiBUS_sparseOmegaCr`, myh, K, matF)
}

fitProxGradCppSeq <- function(ulam, theta, intStepSize, dat, basisMat0, nk, Hp, maxInt, epsilon, shrinkScale, accelrt, numCovs, designMat1, truncation, neg2loglikSat) {
    .Call(`_sparseSOMNiBUS_fitProxGradCppSeq`, ulam, theta, intStepSize, dat, basisMat0, nk, Hp, maxInt, epsilon, shrinkScale, accelrt, numCovs, designMat1, truncation, neg2loglikSat)
}

proximalOperatorCpp <- function(t, lambda1, u_p, nk) {
    .Call(`_sparseSOMNiBUS_proximalOperatorCpp`, t, lambda1, u_p, nk)
}

dot_std <- function(x, y) {
    .Call(`_sparseSOMNiBUS_dot_std`, x, y)
}

dot_arma <- function(x, y) {
    .Call(`_sparseSOMNiBUS_dot_arma`, x, y)
}

proximalOperatorCppOld <- function(t, lambda1, Hp, u_p, nk) {
    .Call(`_sparseSOMNiBUS_proximalOperatorCppOld`, t, lambda1, Hp, u_p, nk)
}

thetaUpdateCpp <- function(stepSize, theta, gBinomLoss, nk, numCovs, lambda1, Hp, basisMat0, dat, designMat1, theta_m, iter, accelrt, truncation) {
    .Call(`_sparseSOMNiBUS_thetaUpdateCpp`, stepSize, theta, gBinomLoss, nk, numCovs, lambda1, Hp, basisMat0, dat, designMat1, theta_m, iter, accelrt, truncation)
}

oneUpdateCpp <- function(theta, stepSize, lambda1, dat, basisMat0, nk, Hp, numCovs, shrinkScale, designMat1, theta_m, iter, accelrt, truncation) {
    .Call(`_sparseSOMNiBUS_oneUpdateCpp`, theta, stepSize, lambda1, dat, basisMat0, nk, Hp, numCovs, shrinkScale, designMat1, theta_m, iter, accelrt, truncation)
}

getSeparateThetaCpp <- function(theta, nk, numCovs) {
    .Call(`_sparseSOMNiBUS_getSeparateThetaCpp`, theta, nk, numCovs)
}

estimatePijCpp <- function(theta, basisMat0, designMat1, nk, numCovs) {
    .Call(`_sparseSOMNiBUS_estimatePijCpp`, theta, basisMat0, designMat1, nk, numCovs)
}

getPrec <- function(x) {
    .Call(`_sparseSOMNiBUS_getPrec`, x)
}

binomObjectCppValueCopy <- function(theta, basisMat0, dat, nk, numCovs, designMat1, truncation) {
    .Call(`_sparseSOMNiBUS_binomObjectCppValueCopy`, theta, basisMat0, dat, nk, numCovs, designMat1, truncation)
}

binomObjectCpp <- function(theta, basisMat0, dat, nk, numCovs, designMat1, truncation) {
    .Call(`_sparseSOMNiBUS_binomObjectCpp`, theta, basisMat0, dat, nk, numCovs, designMat1, truncation)
}

binomObjectCppRef <- function(theta, basisMat0, dat, nk, numCovs, designMat1, truncation) {
    .Call(`_sparseSOMNiBUS_binomObjectCppRef`, theta, basisMat0, dat, nk, numCovs, designMat1, truncation)
}

twoPenaltiesCpp <- function(thetaSep, lambda1, numCovs, nk) {
    .Call(`_sparseSOMNiBUS_twoPenaltiesCpp`, thetaSep, lambda1, numCovs, nk)
}

lambdaMaxCpp <- function(meth, total, designMat1, Hp, numCovs, mu) {
    .Call(`_sparseSOMNiBUS_lambdaMaxCpp`, meth, total, designMat1, Hp, numCovs, mu)
}

designToTilda <- function(designMat1, Linv, numCovs) {
    .Call(`_sparseSOMNiBUS_designToTilda`, designMat1, Linv, numCovs)
}

