# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em4 <- function(y, X, maxit = 10L, nthr = 1L) {
    .Call(`_snpSOMNiBUS_em4`, y, X, maxit, nthr)
}

rcpp_hello_world <- function() {
    .Call(`_snpSOMNiBUS_rcpp_hello_world`)
}

sparseOmegaCr <- function(myh, K, F) {
    .Call(`_snpSOMNiBUS_sparseOmegaCr`, myh, K, F)
}

proximalOperatorCpp <- function(t, lambda1, Hp, u_p, nk) {
    .Call(`_snpSOMNiBUS_proximalOperatorCpp`, t, lambda1, Hp, u_p, nk)
}

dot_std <- function(x, y) {
    .Call(`_snpSOMNiBUS_dot_std`, x, y)
}

dot_arma <- function(x, y) {
    .Call(`_snpSOMNiBUS_dot_arma`, x, y)
}

proximalOperatorCppOld <- function(t, lambda1, Hp, u_p, nk) {
    .Call(`_snpSOMNiBUS_proximalOperatorCppOld`, t, lambda1, Hp, u_p, nk)
}

thetaUpdateCpp <- function(stepSize, theta, gBinomLoss, nk, numCovs, lambda1, Hp, basisMat0, dat, designMat1, theta_m, iter, accelrt, truncation) {
    .Call(`_snpSOMNiBUS_thetaUpdateCpp`, stepSize, theta, gBinomLoss, nk, numCovs, lambda1, Hp, basisMat0, dat, designMat1, theta_m, iter, accelrt, truncation)
}

oneUpdateCpp <- function(theta, stepSize, lambda1, dat, basisMat0, nk, Hp, numCovs, shrinkScale, designMat1, theta_m, iter, accelrt, truncation) {
    .Call(`_snpSOMNiBUS_oneUpdateCpp`, theta, stepSize, lambda1, dat, basisMat0, nk, Hp, numCovs, shrinkScale, designMat1, theta_m, iter, accelrt, truncation)
}

getSeparateThetaCpp <- function(theta, nk, numCovs) {
    .Call(`_snpSOMNiBUS_getSeparateThetaCpp`, theta, nk, numCovs)
}

estimatePijCpp <- function(theta, basisMat0, designMat1, nk, numCovs) {
    .Call(`_snpSOMNiBUS_estimatePijCpp`, theta, basisMat0, designMat1, nk, numCovs)
}

binomObjectCppValueCopy <- function(theta, basisMat0, dat, nk, numCovs, designMat1, truncation) {
    .Call(`_snpSOMNiBUS_binomObjectCppValueCopy`, theta, basisMat0, dat, nk, numCovs, designMat1, truncation)
}

binomObjectCpp <- function(theta, basisMat0, dat, nk, numCovs, designMat1, truncation) {
    .Call(`_snpSOMNiBUS_binomObjectCpp`, theta, basisMat0, dat, nk, numCovs, designMat1, truncation)
}

binomObjectCppRef <- function(theta, basisMat0, dat, nk, numCovs, designMat1, truncation) {
    .Call(`_snpSOMNiBUS_binomObjectCppRef`, theta, basisMat0, dat, nk, numCovs, designMat1, truncation)
}

